CREATE TABLE ORDER_DETAIL
(
   ID SERIAL NOT NULL,
   COMMENTS VARCHAR (255),
   CREATED_BY VARCHAR (255),
   CREATED_DATE TIMESTAMP (6),
   PREPARATION_ORDER_STATUS VARCHAR (255) CHECK
   (
      PREPARATION_ORDER_STATUS IN
      (
         'REQUESTED',
         'READY',
         'PREPARING',
         'RELIVERED'
      )
   ),
   QUANTITY INTEGER NOT NULL,
   REMINING_PREPARATION_TIME TIMESTAMP (6),
   REQUEST_DATE_TIME TIMESTAMP (6),
   START_PREPARATION_DATE_TIME TIMESTAMP (6),
   UPDATED_BY VARCHAR (255),
   UPDATED_DATE TIMESTAMP (6),
   PRODUCT_ID BIGINT,
   PRIMARY KEY (ID)
);
CREATE TABLE PERSON
(
   DTYPE VARCHAR (31) NOT NULL,
   ID SERIAL NOT NULL,
   CITY VARCHAR (255),
   STATE VARCHAR (255),
   STREET VARCHAR (255),
   ZIP_CODE VARCHAR (255),
   CPF VARCHAR (255) NOT NULL,
   CREATED_BY VARCHAR (255),
   CREATED_DATE TIMESTAMP (6),
   DATE_OF_BIRTH TIMESTAMP (6),
   HAS_ACTIVE BOOLEAN NOT NULL,
   NAME VARCHAR (255) NOT NULL,
   OBSERVATIONS VARCHAR (255),
   PHONE VARCHAR (255),
   UPDATED_BY VARCHAR (255),
   UPDATED_DATE TIMESTAMP (6),
   ALLERGIES VARCHAR (255),
   VIP BOOLEAN,
   ADMISSION_DATE TIMESTAMP (6),
   EMPLOYEE_AVIABILITY VARCHAR (255) CHECK
   (
      EMPLOYEE_AVIABILITY IN
      (
         'BUSY',
         'AVAILABLE'
      )
   ),
   MERITAL_STATUS VARCHAR (255) CHECK
   (
      MERITAL_STATUS IN
      (
         'SINGLE',
         'MARRIED',
         'WIDOVED',
         'DIVORCED',
         'SEPARATE'
      )
   ),
   PIS INTEGER NOT NULL,
   RESIGNATION_DATE TIMESTAMP (6),
   RESPONSABILITY VARCHAR (255) CHECK
   (
      RESPONSABILITY IN
      (
         'CLEANER',
         'WAITER',
         'COOK',
         'MANAGER'
      )
   ),
   RG VARCHAR (255) NOT NULL,
   SCHOOLING VARCHAR (255) CHECK
   (
      SCHOOLING IN
      (
         'ELEMENTARY',
         'HIGH',
         'HIGHER'
      )
   ),
   PRIMARY KEY (ID)
);
CREATE TABLE PRODUCT
(
   ID BIGSERIAL NOT NULL,
   CODE VARCHAR (255) NOT NULL,
   COMMENTS VARCHAR (255),
   COST_PRICE FLOAT (53) NOT NULL,
   CREATED_BY VARCHAR (255),
   CREATED_DATE TIMESTAMP (6),
   DESCRIPTION VARCHAR (255) NOT NULL,
   HAS_ACTIVE BOOLEAN NOT NULL,
   NAME VARCHAR (255) NOT NULL,
   PREPARATION_TIME VARCHAR (255),
   PRODUCT_TYPE VARCHAR (255) NOT NULL CHECK
   (
      PRODUCT_TYPE IN
      (
         'SNACK',
         'DRINK',
         'DESSERT'
      )
   ),
   SALE_PRICE FLOAT (53) NOT NULL,
   UPDATED_BY VARCHAR (255),
   UPDATED_DATE TIMESTAMP (6),
   PRIMARY KEY (ID)
);
CREATE TABLE RESTAURANT_TABLE
(
   ID SERIAL NOT NULL,
   CODE VARCHAR (255) NOT NULL,
   CREATED_BY VARCHAR (255),
   CREATED_DATE TIMESTAMP (6),
   NAME VARCHAR (255) NOT NULL,
   NUMBER INTEGER,
   TABLE_STATUS VARCHAR (255) CHECK
   (
      TABLE_STATUS IN
      (
         'RESERVED',
         'OCCUPIED',
         'AVAILABLE'
      )
   ),
   UPDATED_BY VARCHAR (255),
   UPDATED_DATE TIMESTAMP (6),
   EMPLOYEE_ID INTEGER,
   PRIMARY KEY (ID)
);
CREATE TABLE TAB
(
   ID SERIAL NOT NULL,
   CODE VARCHAR (255) NOT NULL,
   COMMENTS VARCHAR (255),
   CREATED_BY VARCHAR (255),
   CREATED_DATE TIMESTAMP (6),
   TAB_STATUS VARCHAR (255) CHECK
   (
      TAB_STATUS IN
      (
         'OPEN',
         'PAID',
         'CLOSED'
      )
   ),
   UPDATED_BY VARCHAR (255),
   UPDATED_DATE TIMESTAMP (6),
   CUSTOMER_ID INTEGER,
   TABLE_ID INTEGER,
   PRIMARY KEY (ID)
);
CREATE TABLE TAB_ORDER_DETAILS
(
   TAB_ID INTEGER NOT NULL,
   ORDER_DETAILS_ID INTEGER NOT NULL
);
ALTER TABLE IF EXISTS ORDER_DETAIL DROP CONSTRAINT IF EXISTS UK_NKB731C2U3FXWULN18O6LYX6U;
ALTER TABLE IF EXISTS ORDER_DETAIL ADD CONSTRAINT UK_NKB731C2U3FXWULN18O6LYX6U UNIQUE (PRODUCT_ID);
ALTER TABLE IF EXISTS PERSON DROP CONSTRAINT IF EXISTS UK_OVIHP2P82C97WBE60MV11TXRJ;
ALTER TABLE IF EXISTS PERSON ADD CONSTRAINT UK_OVIHP2P82C97WBE60MV11TXRJ UNIQUE (CPF);
ALTER TABLE IF EXISTS PERSON DROP CONSTRAINT IF EXISTS UK_AV28NDKB1QD30XO11B7NFA4LD;
ALTER TABLE IF EXISTS PERSON ADD CONSTRAINT UK_AV28NDKB1QD30XO11B7NFA4LD UNIQUE (PIS);
ALTER TABLE IF EXISTS PERSON DROP CONSTRAINT IF EXISTS UK_8SPR6IY5WD8RMDJ97IFVXL1LB;
ALTER TABLE IF EXISTS PERSON ADD CONSTRAINT UK_8SPR6IY5WD8RMDJ97IFVXL1LB UNIQUE (RG);
ALTER TABLE IF EXISTS PRODUCT DROP CONSTRAINT IF EXISTS UK_H3W5R1MX6D0E5C6UM32DGYJEJ;
ALTER TABLE IF EXISTS PRODUCT ADD CONSTRAINT UK_H3W5R1MX6D0E5C6UM32DGYJEJ UNIQUE (CODE);
ALTER TABLE IF EXISTS RESTAURANT_TABLE DROP CONSTRAINT IF EXISTS UK_NCJQO0H763RW9WTG4MMC1KUJ4;
ALTER TABLE IF EXISTS RESTAURANT_TABLE ADD CONSTRAINT UK_NCJQO0H763RW9WTG4MMC1KUJ4 UNIQUE (CODE);
ALTER TABLE IF EXISTS RESTAURANT_TABLE DROP CONSTRAINT IF EXISTS UK_AMQOPFXXVGOL8UEYV3UMXE2TI;
ALTER TABLE IF EXISTS RESTAURANT_TABLE ADD CONSTRAINT UK_AMQOPFXXVGOL8UEYV3UMXE2TI UNIQUE (NAME);
ALTER TABLE IF EXISTS RESTAURANT_TABLE DROP CONSTRAINT IF EXISTS UK_R51HWBVBJ8HFKL1OFIQ3LTW86;
ALTER TABLE IF EXISTS RESTAURANT_TABLE ADD CONSTRAINT UK_R51HWBVBJ8HFKL1OFIQ3LTW86 UNIQUE (NUMBER);
ALTER TABLE IF EXISTS RESTAURANT_TABLE DROP CONSTRAINT IF EXISTS UK_IMJRJ651AK5E5QYW3B9DSWNCW;
ALTER TABLE IF EXISTS RESTAURANT_TABLE ADD CONSTRAINT UK_IMJRJ651AK5E5QYW3B9DSWNCW UNIQUE (EMPLOYEE_ID);
ALTER TABLE IF EXISTS TAB DROP CONSTRAINT IF EXISTS UK_PM7SBNFA2QGF80JO1CXVOE0RS;
ALTER TABLE IF EXISTS TAB ADD CONSTRAINT UK_PM7SBNFA2QGF80JO1CXVOE0RS UNIQUE (CODE);
ALTER TABLE IF EXISTS TAB_ORDER_DETAILS DROP CONSTRAINT IF EXISTS UK_CEXRF6PT8P3O6Q5ECNAT47IJK;
ALTER TABLE IF EXISTS TAB_ORDER_DETAILS ADD CONSTRAINT UK_CEXRF6PT8P3O6Q5ECNAT47IJK UNIQUE (ORDER_DETAILS_ID);
ALTER TABLE IF EXISTS ORDER_DETAIL ADD CONSTRAINT FKB8BG2BKTY0OKSA3WIQ5MP5QNC FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT;
ALTER TABLE IF EXISTS RESTAURANT_TABLE ADD CONSTRAINT FKP5V6AUN4KKD2PNTHRH6FP3OAH FOREIGN KEY (EMPLOYEE_ID) REFERENCES PERSON;
ALTER TABLE IF EXISTS TAB ADD CONSTRAINT FKQN1O2Q113CQ9NTTG741BO5RK FOREIGN KEY (CUSTOMER_ID) REFERENCES PERSON;
ALTER TABLE IF EXISTS TAB ADD CONSTRAINT FK5Q1WEPG1479P2YTWRHR4AGA0V FOREIGN KEY (TABLE_ID) REFERENCES RESTAURANT_TABLE;
ALTER TABLE IF EXISTS TAB_ORDER_DETAILS ADD CONSTRAINT FKDW339T53X57288TVSPCM777LW FOREIGN KEY (ORDER_DETAILS_ID) REFERENCES ORDER_DETAIL;
ALTER TABLE IF EXISTS TAB_ORDER_DETAILS ADD CONSTRAINT FKQK646HRHTPEROGT3Q3DFD7QUP FOREIGN KEY (TAB_ID) REFERENCES TAB;